using System.Xml.Serialization;

namespace ScreenshotMaker.DAL
{
	// autogenerated

	/// <remarks />
	[XmlType(AnonymousType = true)]
	[XmlRoot(Namespace = "", IsNullable = false)]
	public class rss
	{
		/// <remarks />
		public rssChannel channel { get; set; }

		/// <remarks />
		[XmlAttribute]
		public decimal version { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannel
	{
		/// <remarks />
		public rssChannelItem item { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItem
	{
		/// <remarks />
		public string title { get; set; }

		/// <remarks />
		[XmlArrayItem("customfield", IsNullable = false)]
		public rssChannelItemCustomfield[] customfields { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfield
	{
		/// <remarks />
		public string customfieldname { get; set; }

		/// <remarks />
		public rssChannelItemCustomfieldCustomfieldvalues customfieldvalues { get; set; }

		/// <remarks />
		[XmlAttribute]
		public string id { get; set; }

		/// <remarks />
		[XmlAttribute]
		public string key { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvalues
	{
		/// <remarks />
		public string customfieldvalue { get; set; }

		/// <remarks />
		[XmlArrayItem("step", IsNullable = false)]
		public rssChannelItemCustomfieldCustomfieldvaluesStep[] steps { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvaluesStep
	{
		/// <remarks />
		public byte index { get; set; }

		/// <remarks />
		public rssChannelItemCustomfieldCustomfieldvaluesStepStep step { get; set; }

		/// <remarks />
		public rssChannelItemCustomfieldCustomfieldvaluesStepData data { get; set; }

		/// <remarks />
		public rssChannelItemCustomfieldCustomfieldvaluesStepResult result { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvaluesStepStep
	{
		/// <remarks />
		public rssChannelItemCustomfieldCustomfieldvaluesStepStepP p { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvaluesStepStepP
	{
		/// <remarks />
		[XmlElement("br")]
		public object[] br { get; set; }

		/// <remarks />
		[XmlText]
		public string[] Text { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvaluesStepData
	{
		/// <remarks />
		public rssChannelItemCustomfieldCustomfieldvaluesStepDataUL ul { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvaluesStepDataUL
	{
		/// <remarks />
		[XmlElement("li")]
		public string[] li { get; set; }

		/// <remarks />
		[XmlAttribute]
		public string @class { get; set; }

		/// <remarks />
		[XmlAttribute]
		public string type { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvaluesStepResult
	{
		/// <remarks />
		public rssChannelItemCustomfieldCustomfieldvaluesStepResultP p { get; set; }
	}

	/// <remarks />
	[XmlType(AnonymousType = true)]
	public class rssChannelItemCustomfieldCustomfieldvaluesStepResultP
	{
		/// <remarks />
		[XmlElement("br")]
		public object[] br { get; set; }

		/// <remarks />
		[XmlText]
		public string[] Text { get; set; }
	}
}